--INSERT INTO categoria (nome, descricao) VALUES ('Eletrônicos', 'Dispositivos eletrônicos e gadgets');
--INSERT INTO categoria (nome, descricao) VALUES ('Livros', 'Livros de diversos gêneros');
--INSERT INTO categoria (nome, descricao) VALUES ('Roupas', 'Vestuário e acessórios');
